#!/bin/sh
if [ \( "$1" = "--help" \) -o \( $# -ne 1 \) ]; then
	echo "usage: update <package>"
	echo
	echo "Example: update superfinapi-1.0.0"
	echo
	exit 1
fi
rm -v $1.*
echo -n "Downloading $1.md5 .."
tftp -g -l $1.md5 -r blackfin/$1.md5 repos.lco.gtn &
lastsize='-1'
size=`ls -l $1.md5 | awk '{printf $5}'`
until [ "$size" = "$lastsize" ]; do
        echo -n "."
        sleep 1
        lastsize="$size"
        size=`ls -l $1.md5 | awk '{printf $5}'`
done
echo
echo "Download complete."
echo -n "Downloading $1.tgz .."
tftp -g -l $1.tgz -r blackfin/$1.tgz repos.lco.gtn &
lastsize='-1'
size=`ls -l $1.tgz | awk '{printf $5}'`
until [ "$size" = "$lastsize" ]; do
        echo -n "."
        sleep 1
        lastsize="$size"
        size=`ls -l $1.tgz | awk '{printf $5}'`
done
echo
echo "Download complete."
md5sum -c $1.md5
